# Copyright (c) 2024 Winford (Uncle Grumpy) <winford@object.stream>
# SPDX-License-Identifier: CC0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
